name: Deploy

on:
  push:
      branches:
          - main

jobs:
  build-dashboard:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: cd dashboard && npm install
    - name: Build
      env:
        CI: false
        REACT_APP_API_BASEURL: ${{ secrets.API_BASEURL }}
        REACT_APP_EMOTE_ASSET_BASEURL: ${{ secrets.EMOTE_ASSET_BASEURL }}
        REACT_APP_TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        REACT_APP_TWITCH_LOGIN_REDIRECT_URI: ${{ secrets.TWITCH_LOGIN_REDIRECT_URI }}
      run: cd dashboard && npm run build
    - name: Upload artificats
      uses: actions/upload-artifact@v1
      with:
        name: dashboard
        path: dashboard/build
  deploy:
    runs-on: ubuntu-latest
    needs: build-dashboard
    steps:
    - name: Setup Deployment
      env:
        SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_PRIVATE_KEY" >> ~/.ssh/server
        chmod 600 ~/.ssh/server
        echo -e "Host server\n\tHostName $SERVER_IP\n\tPort $SSH_PORT\n\tIdentityFile ~/.ssh/server\n\tUser $SERVER_USER" >> ~/.ssh/config
        ssh-keyscan -p "$SSH_PORT" -H "$SERVER_IP" >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/config
        sudo apt-get update -y
        sudo apt-get -y install rsync
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: dashboard
    - name: Deploy
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      run: |
        ssh server -f "rm -rf $PROJECT_PATH/dashboard/build"
        mv dashboard build
        rsync -a ./build server:$PROJECT_PATH/dashboard
